import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar';
import Chat from './components/chat';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chat Bot Diskominfotik',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script defer src="https://app.fastbots.ai/embed.js" data-bot-id="clyicd9lg0017nibc5df3rzjn"></script>
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        {/* <Chat /> */}
        <iframe style={{ width: '400px', maxHeight: '600px' }} className="hidden" src="https://app.fastbots.ai/embed/clyicd9lg0017nibc5df3rzjn"></iframe>
      </body>
    </html>
  );
}
